#!/bin/bash

set -e

# expires july 16th
b64token="ZG9wX3YxXzI5NWQ5MjI3MmZkNTM3NTc3MzYxODJlMjVlOWYwMTI4ZTFhYTFjZjVlYzljMWM0YTIzNzA0YTRmMjhjNjViOGQ="

clear

digitalOceanInfo=$(doctl compute droplet list --format Name,PublicIPv4 -t "$(echo -n $b64token | base64 -d)" | grep -v "omni" | grep -v "Name" | gum choose)

clear

gum style \
	--foreground 140 --border-foreground 100 --border double \
	--align middle --width 100 --margin="1 2" --padding="2 4" \
  "DigitalOcean Talos Virtual Machines

$digitalOceanInfo"
